### ISSUE TITLE
At least you should provide the right format of your dataset

### ISSUE THREAD

**Issue by zkvii** [surika/DiffusEmp#2]
the required dataset in your  code is .jsonl, but provided dataset in remote netdisk is .csv,
```
--data_dir /path-to-repo/DiffusEmp/datasets/EmpatheticDialogue/mask-fine 

######
    if split == 'train':
        print('### Loading form the TRAIN set...')
        path = f'{data_args.data_dir}/train.jsonl'
    elif split == 'valid':
        print('### Loading form the VALID set...')
        path = f'{data_args.data_dir}/valid.jsonl'
    elif split == 'test':
        print('### Loading form the TEST set...')
        path = f'{data_args.data_dir}/test.jsonl'
    else:
        assert False, "invalid split for dataset"

```
where is the script for processing these data.

**Comment by surika** [comment]
Thank you for pointing out our oversight. We have uploaded the required .jsonl format datasets and provided the corresponding links. Please use the following links to download the datasets:

https://drive.google.com/file/d/1tUekqAUDAQCvbPJ2VD70dPEkjua2VaMg/view?usp=sharing

**Comment by zkvii** [comment]
Thank you for your prompt response. Wishing you all the best.
